version: '2'
services:
  web:
    container_name: web
    build: .
    image: web
    command: npm start
    volumes:
#      - .:/usr/app/
#      - /usr/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - mysql
      #- adminer
      - redis
    environment:
      PORT: 3000
      NODE_ENV: development
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: chbb_chatbot_dev

  mysql:
    image: mysql
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
#      MYSQL_USER: Pwcwelcome0
#      MYSQL_PASSWORD: Pwcwelcome0
      MYSQL_DATABASE: chbb_chatbot_dev
    volumes:
      - ./data/mysql:/var/lib/mysql
    ports:
      - "3306:3306"

## Database management in a single PHP file.
#  adminer:
#    image: adminer
#    restart: always
#    ports:
#      - 8080:8080

  redis:
    image: redis
    container_name: redis
    volumes:
      - ./data/redis:/data
    ports:
      - "6379:6379"